services:
  app:
    build: 
      dockerfile: ./Dockerfile
      target: server # server - для продакшена, dev - для разработки
      args:
        - POETRY_VERSION=${POETRY_VERSION}
    volumes:
      - .env:/app/.env
      - ./src:/app/src
      - ./alembic:/app/alembic
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
      - ./Dockerfile:/app/Dockerfile
    ports:
      - "8080:8080"
      - "5678:5678"
  
    depends_on:
      - db
    env_file:
      - .env
  
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: ${POSTGRES__POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES__POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES__POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES__POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES__POSTGRES_PASSWORD}

    env_file:
      - .env

  minio:
    container_name: minio
    image: minio/minio:latest
    entrypoint: /bin/sh
    command: -c "mkdir -p /data/private-bucket && minio server /data --console-address ':9001'"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO__MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO__MINIO_ROOT_PASSWORD}
      # MINIO_ACCESS_KEY: ${MINIO__MINIO_ACCESS_KEY}
      # MINIO_SECRET_KEY: ${MINIO__MINIO_SECRET_KEY}


volumes:
  minio_data: